/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    DesktopOutlined: typeof import('@ant-design/icons-vue')['DesktopOutlined'];
    FileOutlined: typeof import('@ant-design/icons-vue')['FileOutlined'];
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default'];
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default'];
    PieChartOutlined: typeof import('@ant-design/icons-vue')['PieChartOutlined'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TeamOutlined: typeof import('@ant-design/icons-vue')['TeamOutlined'];
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default'];
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined'];
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default'];
  }
}
